### ISSUE TITLE
Words getting jumbled when switching the tabs.

### ISSUE THREAD

**Issue by princeyesuraj** [benrlodge/wordTypeErase#2]
When you are on different tab and open the respective tab which is using the plugin sometimes the words are jumbled.

data-pos is fine but not displayed in order.

This also causes bug in highlighting where partially some texts are highligted  already.

I am using Firefox 35
![partillly highligted tex on type](https://cloud.githubusercontent.com/assets/2167618/5773281/51f7b8ee-9d86-11e4-9b68-987d2b38033b.png)
![jumbled words](https://cloud.githubusercontent.com/assets/2167618/5773284/5f1d5f24-9d86-11e4-8f96-5c589147d91a.png)

**Comment by benrlodge** [comment]
Hey @princeyesuraj - this was a known issue that I just haven't had time to address. For a quick temporary fix I've updated the plugin so when the user navigates away from the tab and returns, all timers are cleared and the text is replaced with the the last word/phrase in the list. In the future I will update the plugin to restart the looping entirely. 
Update: https://github.com/benrlodge/wordTypeErase/commit/17478f66d2a00f226ead502a55e11afed4acb909
